package pl.dcrft.Managers.Statistic;

public enum StatisticType {
    SURVIVAL_KILLS,
    SURVIVAL_DEATHS,
    SURVIVAL_KDR,
    SURVIVAL_BLOCKS,
    SKYBLOCK_LEVEL,
    SKYBLOCK_MONEY,
    SURVIVAL_TIMEPLAYED,
    SURVIVAL_MARRY,


    SKYBLOCK_KILLS,
    SKYBLOCK_DEATHS,
    SKYBLOCK_KDR,
    SKYBLOCK_TIMEPLAYED,
    SKYBLOCK_MARRY,


    RANK,
    SINCE,
    ONLINE
}
